apiVersion: v1
kind: Service
metadata:
  name: my-sql-app-service
spec:
  type: NodePort
  selector:
    app: my-sql-app
  ports:
    - protocol: TCP
      port: 6655
      targetPort: 6655
      nodePort: 30005  # Choose a port between 30000-32767
